In [ ]:
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from matplotlib.pyplot import specgram
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import seaborn as sns
import keras
from keras.callbacks import ReduceLROnPlateau
from keras.models import Sequential
from keras.layers import Dense, Conv1D, LSTM, MaxPooling1D, Flatten, Dropout, BatchNormalization
from keras.utils import to_categorical
from keras.callbacks import ModelCheckpoint
from keras import regularizers
import os
import glob
import pandas as pd
import IPython.display as ipd
import plotly.express as px
import scipy.io.wavfile
import sys
import warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
#Xuất dữ liệu
RAV = 'RAVDESS/audio_speech_actors_01-24/'
dir_list = os.listdir(RAV)

emotion = [] #biểu thị cảm xúc của âm thanh
gender = [] #giới tính của người nói
path = [] #đường dẫn đến file âm thanh tương ứng
feature = []
#Phân tích tên file âm thanh để trích xuất thông tin về cảm xúc và giới tính của người nói.
for i in dir_list:
    fname = os.listdir(RAV + i)
    for f in fname:
        part = f.split('.')[0].split('-')
        emotion.append(int(part[2]))
        temp = int(part[6])
        if temp%2 == 0:
            temp = "female"
        else:
            temp = "male"
        gender.append(temp)
        path.append(RAV + i + '/' + f)

#Xây dựng DataFrame RAV_df từ các thông tin đã trích xuất
RAV_df = pd.DataFrame(emotion)
RAV_df = RAV_df.replace({1:'neutral', 2:'calm', 3:'happy', 4:'sad', 5:'angry', 6:'fear', 7:'disgust', 8:'surprise'})
RAV_df = pd.concat([pd.DataFrame(gender),RAV_df],axis=1)
RAV_df.columns = ['gender','emotion']
RAV_df['labels'] =RAV_df.gender + '_' + RAV_df.emotion
RAV_df['source'] = 'RAVDESS'
RAV_df = pd.concat([RAV_df,pd.DataFrame(path, columns = ['path'])],axis=1)
#Loại bỏ cột 'gender' và hiển thị số lượng mẫu dữ liệu cho mỗi nhãn cảm xúc.
RAV_df = RAV_df.drop(['gender'], axis=1)
RAV_df.labels.value_counts()

labels
male_calm          96
male_happy         96
male_fear          96
male_disgust       96
male_sad           96
male_angry         96
male_surprise      96
female_calm        96
female_surprise    96
female_happy       96
female_fear        96
female_disgust     96
female_sad         96
female_angry       96
male_neutral       48
female_neutral     48
Name: count, dtype: int64

In [ ]:
# Hàm làm nhiễu âm thanh
def noise(data):
    noise_amp = 0.035*np.random.uniform()*np.amax(data)
    data = data + noise_amp*np.random.normal(size=data.shape[0])
    return data

# Hàm kéo dài âm thanh
def stretch(data, rate=0.8):
    return librosa.effects.time_stretch(data, rate = rate)

# Hàm nhấn mạnh/thấp âm thanh
def pitch(data, sampling_rate, pitch_factor=0.7):
   # return librosa.effects.pitch_shift(data, sampling_rate, pitch_factor)
    return librosa.effects.pitch_shift(y=data, sr=sampling_rate, n_steps=pitch_factor)

path = np.array(RAV_df.path)[1]
data, sample_rate = librosa.load(path)

In [ ]:
# Hàm trích xuất các đặc trưng từ dữ liệu
def extract_features(data):
    # ZCR: Tần số băng qua không là tốc độ tín hiệu thay đổi từ dương sang 0 sang âm hoặc từ âm sang 0 sang dương
    result = np.array([])
    zcr = np.mean(librosa.feature.zero_crossing_rate(y=data).T, axis=0)
    result=np.hstack((result, zcr))

    # Chroma_stft : Thể hiện phân bố tần số của các nốt nhạc trong tín hiệu âm thanh.
    stft = np.abs(librosa.stft(data))
    chroma_stft = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T, axis=0)
    result = np.hstack((result, chroma_stft))

    # MFCC : Là một bộ các đặc trưng được sử dụng phổ biến trong xử lý tín hiệu âm thanh
    mfcc = np.mean(librosa.feature.mfcc(y=data, sr=sample_rate).T, axis=0)
    result = np.hstack((result, mfcc))

    # Root Mean Square Value: Là một đại lượng thể hiện sức mạnh trung bình của tín hiệu âm thanh trong mỗi cửa sổ thời gian
    rms = np.mean(librosa.feature.rms(y=data).T, axis=0)
    result = np.hstack((result, rms))

    # MelSpectogram : là biểu diễn trực quan của phổ tần số của tín hiệu âm thanh,
    #trong đó các tần số được biểu diễn trên trục y dưới dạng các băng thông mel thay vì Hz.
    mel = np.mean(librosa.feature.melspectrogram(y=data, sr=sample_rate).T, axis=0)
    result = np.hstack((result, mel))

    return result
# Hàm trích xuất các đặc trưng từ dữ liệu âm-thanh
def get_features(path):
    # Xử lý thời lượng và độ lệch được sử dụng để xử lý phần không có âm thanh khi bắt đầu và kết thúc của mỗi tệp âm thanh
    data, sample_rate = librosa.load(path, duration=2.5, offset=0.6)

    # Với không tăng cường
    res1 = extract_features(data)
    result = np.array(res1)

    # làm nhiễu dữ liệu
    noise_data = noise(data)
    res2 = extract_features(noise_data)
    result = np.vstack((result, res2))

    # kéo dãn và nhấn mạnh/thấp của âm thanh
    new_data = stretch(data)
    data_stretch_pitch = pitch(new_data, sample_rate)
    res3 = extract_features(data_stretch_pitch)
    result = np.vstack((result, res3))

    return result

In [ ]:
# Thêm cảm xúc 3 lần vì đã thực hiện 3 kỹ thuật
# tăng cường trên mỗi tệp âm thanh
X, Y = [], []
for path, emotion in zip(RAV_df.path, RAV_df.emotion):
    feature = get_features(path)
    for ele in feature:
        X.append(ele)
        Y.append(emotion)

In [ ]:
#mã trả về kích thước của X, Y và số lượng đường dẫn âm thanh trong RAV_df
len(X), len(Y), RAV_df.path.shape

(4320, 4320, (1440,))

In [ ]:
Features = pd.DataFrame(X)
Features['labels'] = Y
Features.to_csv('features.csv', index=False)

In [ ]:
#Hiển thị một số dòng đầu tiên và thống kê
display(Features.head())
display(Features.describe())

,0,1,2,3,4,5,6,7,8,9,...,153,154,155,156,157,158,159,160,161,labels
0,0.178354,0.810467,0.707073,0.600536,0.604771,0.648013,0.626874,0.597224,0.663339,0.611452,...,0.000007,0.000007,0.000005,0.000006,4.284741e-06,3.988983e-06,2.407329e-06,8.899194e-07,5.797154e-08,calm
1,0.244113,0.833011,0.769919,0.685230,0.672871,0.730226,0.707466,0.643585,0.701534,0.667796,...,0.000010,0.000010,0.000009,0.000009,7.154689e-06,7.024819e-06,5.463309e-06,4.067468e-06,3.150575e-06,calm
2,0.155165,0.798484,0.703550,0.579219,0.577016,0.626991,0.629416,0.593090,0.621296,0.578494,...,0.000001,0.000001,0.000002,0.000001,1.141171e-06,1.048393e-06,8.726456e-07,4.501752e-07,2.529665e-08,calm
3,0.190448,0.694625,0.730583,0.733133,0.739128,0.721110,0.699378,0.653086,0.710711,0.744858,...,0.000003,0.000003,0.000002,0.000001,8.644034e-07,6.660677e-07,4.428955e-07,2.127365e-07,1.714209e-08,calm
4,0.298362,0.762934,0.813067,0.825032,0.807019,0.816541,0.797787,0.705642,0.719028,0.785051,...,0.000006,0.000006,0.000006,0.000005,4.351570e-06,4.316964e-06,3.867805e-06,3.606170e-06,3.340686e-06,calm

,0,1,2,3,4,5,6,7,8,9,...,152,153,154,155,156,157,158,159,160,161
count,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,4320.000000,...,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03,4.320000e+03
mean,0.211121,0.628428,0.631577,0.636531,0.646507,0.635523,0.606690,0.601078,0.620231,0.637284,...,1.779771e-03,1.793143e-03,1.831893e-03,1.864603e-03,1.916061e-03,1.950074e-03,1.949950e-03,1.905177e-03,1.411315e-03,7.784153e-04
std,0.069117,0.088274,0.097486,0.100497,0.102293,0.104690,0.091320,0.078644,0.080453,0.079320,...,6.240931e-03,6.355623e-03,6.476028e-03,6.611748e-03,6.862573e-03,6.875121e-03,6.793565e-03,6.474040e-03,5.460085e-03,4.387025e-03
min,0.060091,0.339261,0.287322,0.274451,0.261138,0.263614,0.269487,0.262952,0.242573,0.269642,...,2.135466e-08,1.692912e-08,2.129327e-08,2.400430e-08,2.899627e-08,2.325185e-08,6.041326e-08,7.742912e-08,3.497832e-08,2.159462e-09
25%,0.154699,0.569826,0.566439,0.566941,0.576088,0.565761,0.550482,0.554671,0.569795,0.585708,...,2.889440e-05,2.915450e-05,3.025457e-05,3.169591e-05,3.468735e-05,3.388159e-05,3.454783e-05,3.352481e-05,2.002263e-05,2.042758e-06
50%,0.202447,0.632453,0.637594,0.642649,0.653017,0.643769,0.616098,0.609397,0.626726,0.644084,...,1.689116e-04,1.695381e-04,1.719652e-04,1.836441e-04,1.873425e-04,1.839164e-04,1.890032e-04,1.839554e-04,1.161665e-04,1.467828e-05
75%,0.268904,0.692666,0.701654,0.709678,0.722579,0.709448,0.670835,0.655954,0.678216,0.692803,...,8.872470e-04,8.834441e-04,9.528763e-04,9.190238e-04,9.475904e-04,9.537891e-04,9.481863e-04,9.470188e-04,6.167429e-04,1.152594e-04
max,0.406639,0.875499,0.879135,0.901239,0.907017,0.903683,0.880184,0.813967,0.825856,0.868189,...,1.053029e-01,1.098827e-01,1.089929e-01,9.879018e-02,1.142716e-01,1.079606e-01,1.240226e-01,1.042664e-01,9.820467e-02,8.280677e-02

In [ ]:
# Xác định dữ liệu đầu vào và đầu ra
X = Features.iloc[:, :-1].values  # Ma trận đặc trưng
Y = Features['labels'].values     # Vector nhãn

# Mã hóa nhãn sang dạng one-hot
encoder = OneHotEncoder()
Y_encoded = encoder.fit_transform(np.array(Y).reshape(-1,1)).toarray()

# Phân chia dữ liệu thành tập huấn luyện và tập kiểm tra
x_train, x_test, y_train, y_test = train_test_split(X, Y_encoded, random_state=0, shuffle=True)

# Chuẩn hóa dữ liệu
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Mở rộng số chiều của dữ liệu
x_train_reshaped = np.expand_dims(x_train_scaled, axis=2)  # Tập huấn luyện
x_test_reshaped = np.expand_dims(x_test_scaled, axis=2)    # Tập kiểm tra

In [ ]:
# Mô hình LSTM
model_lstm = Sequential()

model_lstm.add(Conv1D(128, kernel_size=3, strides=1, padding='same', activation='relu'))
model_lstm.add(BatchNormalization())
model_lstm.add(MaxPooling1D(pool_size=3, strides=2, padding='same'))

model_lstm.add(Conv1D(64, kernel_size=3, strides=1, padding='same', activation='relu'))
model_lstm.add(BatchNormalization())
model_lstm.add(MaxPooling1D(pool_size=3, strides=2, padding='same'))

model_lstm.add(Conv1D(32, kernel_size=3, strides=1, padding='same', activation='relu'))
model_lstm.add(BatchNormalization())
model_lstm.add(MaxPooling1D(pool_size=3, strides=2, padding='same'))

model_lstm.add(Flatten())
model_lstm.add(Dense(128, activation='relu'))
model_lstm.add(BatchNormalization())
model_lstm.add(Dropout(0.2))

model_lstm.add(Dense(64, activation='relu'))
model_lstm.add(Dense(32, activation='relu'))

model_lstm.add(Dense(8, activation='softmax'))
model_lstm.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model_lstm.build(input_shape=(None, x_train_reshaped.shape[1], 1))
model_lstm.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_8 (Conv1D)               │ (None, 162, 128)       │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 162, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_8 (MaxPooling1D)  │ (None, 81, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_9 (Conv1D)               │ (None, 81, 64)         │        24,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 81, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_9 (MaxPooling1D)  │ (None, 41, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_10 (Conv1D)              │ (None, 41, 32)         │         6,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_7           │ (None, 41, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_10 (MaxPooling1D) │ (None, 21, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 672)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 128)            │        86,144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_8           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 8)              │           264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 129,480 (505.78 KB)

 Trainable params: 128,776 (503.03 KB)

 Non-trainable params: 704 (2.75 KB)

In [ ]:
# Mô hình CNN
model_cnn = Sequential()
model_cnn.add(Conv1D(256, kernel_size=5, strides=1, padding='same', activation='relu', input_shape=(x_train.shape[1], 1)))
model_cnn.add(MaxPooling1D(pool_size=5, strides = 2, padding = 'same'))

model_cnn.add(Conv1D(128, kernel_size=5, strides=1, padding='same', activation='relu'))
model_cnn.add(MaxPooling1D(pool_size=5, strides = 2, padding = 'same'))

model_cnn.add(Conv1D(64, kernel_size=5, strides=1, padding='same', activation='relu'))
model_cnn.add(MaxPooling1D(pool_size=5, strides = 2, padding = 'same'))
model_cnn.add(Dropout(0.2))

model_cnn.add(Conv1D(32, kernel_size=5, strides=1, padding='same', activation='relu'))
model_cnn.add(MaxPooling1D(pool_size=5, strides = 2, padding = 'same'))

model_cnn.add(Flatten())
model_cnn.add(Dense(units=16, activation='relu'))
model_cnn.add(Dropout(0.3))

model_cnn.add(Dense(units=8, activation='softmax'))
model_cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model_cnn.build(input_shape=(None, x_train.shape[1], 1))
model_cnn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 162, 256)       │         1,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 81, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 81, 128)        │       163,968 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 41, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_4 (Conv1D)               │ (None, 41, 64)         │        41,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 21, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 21, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_5 (Conv1D)               │ (None, 21, 32)         │        10,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_5 (MaxPooling1D)  │ (None, 11, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 352)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │         5,648 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 8)              │           136 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 222,584 (869.47 KB)

 Trainable params: 222,584 (869.47 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
y_pred_lstm = np.argmax(model_lstm.predict(x_test_reshaped), axis=1)
y_pred_cnn = np.argmax(model_cnn.predict(x_test_reshaped), axis=1)
y_test_labels = np.argmax(y_test, axis=1)

34/34 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step
34/34 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step

In [ ]:
from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(np.argmax(y_train, axis=1))
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=np.argmax(y_train, axis=1)
)
class_weight_dict = dict(enumerate(class_weights))
print("Class weights:", class_weight_dict)

Class weights: {0: np.float64(0.9246575342465754), 1: np.float64(0.9310344827586207), 2: np.float64(0.9331797235023042), 3: np.float64(0.9440559440559441), 4: np.float64(0.9735576923076923), 5: np.float64(1.9103773584905661), 6: np.float64(0.9353348729792148), 7: np.float64(0.9142212189616253)}

In [ ]:
from keras.callbacks import EarlyStopping, ModelCheckpoint

callbacks_lstm = [
    ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                      patience=5, min_lr=1e-7, verbose=1),
    EarlyStopping(monitor='val_loss', patience=15,
                  restore_best_weights=True, verbose=1),
    ModelCheckpoint('best_lstm.keras', save_best_only=True,
                    monitor='val_loss', verbose=1)
]

history_lstm = model_lstm.fit(
    x_train_reshaped, y_train,
    batch_size=32,         # giảm batch size
    epochs=100,
    validation_data=(x_test_reshaped, y_test),
    class_weight=class_weight_dict,
    callbacks=callbacks_lstm
)

In [ ]:
callbacks_cnn = [
    ReduceLROnPlateau(factor=0.4, patience=4, min_lr=0.0000001),
    EarlyStopping(patience=10, restore_best_weights=True),
    ModelCheckpoint('best_cnn.h5', save_best_only=True, monitor='val_accuracy')
]

history_cnn = model_cnn.fit(
    x_train_reshaped, y_train,
    batch_size=64,
    epochs=80,
    validation_data=(x_test_reshaped, y_test),
    class_weight=class_weight_dict,
    callbacks=callbacks_cnn
)

In [ ]:
# Đánh giá hiệu suất của mô hình LSTM trên tập dữ liệu kiểm tra và in ra giá trị của loss và accuracy
loss_lstm, accuracy_lstm = model_lstm.evaluate(x_test_reshaped, y_test)
print("LSTM Model - Loss: {:.4f}, Accuracy: {:.2f}%".format(loss_lstm, accuracy_lstm * 100))

In [ ]:
# Đánh giá hiệu suất của mô hình CNN trên tập dữ liệu kiểm tra và in ra giá trị của loss và accuracy
loss_cnn, accuracy_cnn = model_cnn.evaluate(x_test_reshaped, y_test)
print("CNN Model - Loss: {:.4f}, Accuracy: {:.2f}%".format(loss_cnn, accuracy_cnn * 100))

In [ ]:
# Chỉnh lại nhãn sau khi dự đoán từ số sang chữ
labels_mapping = {0: 'neutral',1: 'calm', 2: 'happy', 3: 'sad', 4: 'angry', 5: 'fear', 6: 'disgust', 7: 'surprise'}

# Dự đoán nhãn từ chỉ số dự đoán của mô hình LSTM và CNN
y_pred_lstm_labels = [labels_mapping[idx] for idx in y_pred_lstm]
y_pred_cnn_labels = [labels_mapping[idx] for idx in y_pred_cnn]
y_test_labels = [labels_mapping[idx] for idx in y_test_labels]

In [ ]:
# Tạo và in ra báo cáo phân loại, so sánh giữa nhãn thực tế và nhãn dự đoán của mô hình LSTM
print("LSTM Model Classification Report:")
print(classification_report(y_test_labels, y_pred_lstm_labels))

In [ ]:
# Tạo và in ra báo cáo phân loại, so sánh giữa nhãn thực tế và nhãn dự đoán của mô hình CNN
print("CNN Model Classification Report:")
print(classification_report(y_test_labels, y_pred_cnn_labels))

In [ ]:
import joblib
from keras.models import load_model

# Load đúng file .keras vừa train
best_lstm = load_model('best_lstm.keras')

# Compile lại để tránh warning
best_lstm.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Evaluate
loss, acc = best_lstm.evaluate(x_test_reshaped, y_test, verbose=0)
print(f"Best LSTM — Loss: {loss:.4f}, Accuracy: {acc*100:.2f}%")

# Classification report
y_pred = np.argmax(best_lstm.predict(x_test_reshaped), axis=1)
y_true = np.argmax(y_test, axis=1)

labels_mapping = {0:'neutral', 1:'calm', 2:'happy', 3:'sad',
                  4:'angry', 5:'fear', 6:'disgust', 7:'surprise'}

y_pred_labels = [labels_mapping[i] for i in y_pred]
y_true_labels = [labels_mapping[i] for i in y_true]

print("\nBest LSTM Classification Report:")
print(classification_report(y_true_labels, y_pred_labels))

# Save artifacts
best_lstm.save('emotion_recognition_model_LSTM.h5')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(encoder, 'encoder.pkl')
print("✅ Saved!")

Best LSTM — Loss: 1.0450, Accuracy: 67.22%
34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Best LSTM Classification Report:
              precision    recall  f1-score   support

       angry       0.68      0.63      0.65       160
        calm       0.78      0.70      0.74       141
     disgust       0.58      0.55      0.56       143
        fear       0.47      0.75      0.58        76
       happy       0.69      0.58      0.63       142
     neutral       0.78      0.79      0.79       138
         sad       0.73      0.65      0.69       147
    surprise       0.66      0.78      0.71       133

    accuracy                           0.67      1080
   macro avg       0.67      0.68      0.67      1080
weighted avg       0.68      0.67      0.67      1080

✅ Saved!